const paragraphs = [
  "I explained to him that his problems followed logical and directly from his self-destructive major premise.To change his life, he had to establish a new major premise in his thinking.He needed to accept as true the conviction that the infinite intelligence of his subconscious mind was guiding, directing, and prospering him spiritually, mentally, and materially.Once he did that,his subconscious mind would automatically direct him wisely in his decisions,heal his body, and restore his mind to peace and tranquility ",

  "As an adult, however, you are able to make choices.You can use constructive autosuggestion, which is a reconditioning theraphy, to change the impressions made on you in the past. The first step is to make yourself aware of the heterosuggestions that are operating on you. Unexamined, they can create behavior patterns that cause failure in your personal and social loife.Constructive autosuggestion can release you from the mass of negative verbal conditioning that might otherwise distort your life pattern, making  the development of good habits difficult or even impossible.",

  "Your conscious mind is sometimes referred to as your objective ming because it deals with outward object. The objective mind is aware of the objective world. Its media of observation are you five physical senses. Your objective mind is your guide and director in your contact with your environment. You gain knowledge through your five senses. Your objective mind learns through observation, experience, and education. As previously pointed out, the greatest function of the objective mind is that of reasoning.",

  "Psychologists and other have performed countless experiments on people who are in a hypnotic trance.This research shows clearly that the subconscious mind does not make the selection and comparisons that are necessary for a resoning process. Your subconscious, however false. Having once accepted any suggestion, it responds according to the nature of the suggestion given. To illustrate how suggestible your subconscious mind is , if a practiced hypnotist suggests to one of her subject that she is Napolean Bonaparte, or even cat or a dog ,the subject will act out the pan with inimitable accuracy.",

  "This mother prayer had an interesting sequel. Shortly after she began to pray in the way just described, she met a former employer on the street whom she had not seen in five years.The former employer offered her a responsible, well-paid position. He even advanced  her a temperoroy loan to tide her over until her first checkpays. As she said to me, I'll never forget the amazing power of thank you, father. It has worked wonders for me.The effectiveness of an affirmation is determined largely by your understanding of the truth and meaning that undrlie the word.",

  "In a coherent paragraph, each sentence relates clearly to the topic sentence or controlling idea, but there is more to coherence than this. If a paragraph is coherent, each sentence flows smoothly into next without obvious shifts or jumps.A coherent paragraph also highlights the ties between old information and new information to make the structure of idea or arguments clear to the reader",

  "Be consistent in point of view, verb tense , and numbers. Consistency in point of view,verb tense, and number is a subtle but important aspect of coherence. If you shift from the more personal you to impersonal one ,from past present tense, or from a man to they for example you make your paragraph less coherent.Such inconsistencies can also confuse your reader and make your argument more difficlut to follow.",

  "Use transition words or phrase between sentences and between paragraphs.Transitional expressions emphasize the relationship between ideas, so they help reader follow your train of thought ot see connections that they might otherwise miss or misunderstand. The following paragraph shows how carefully chosen transitions lead the reader smoothly from the introduction to the conclusion of the paragraph.A number of other techniques that you can use to establish coherence in paragraph are described below.",

  "Create parallel structures. Parallel structures are created by constructing two or more phrases or sentences that have the same grammatical structure and use the same parts of speech.By creating parallel structure you make your sentences clear and easier to read. In addition,repeating a pattern in series of consecutive sentences helps your reader see the connections between ideas.In the paragraph above about scientists and the sence of sight,several sentences in the body of the paragraph have been constructed in parallel way.",

  "Let’s begin by defining this concept of the paragraph. A paragraph is a group of sentences that present, develop, and support a single idea in a continual block of sentences with no line breaks. There may be a prescribed length or number of sentences according to the assignment you’ve been given.Paragraphs rarely stand alone, so most often the main topic of the paragraph serves the main concept or purpose of a large whole.",

  "What if I told you that the topic sentence doesn’t necessarily need to be at the beginning? This might be contrary to what you’ve learned in previous English or writing classes, and that’s okay. Certainly, placing topic sentences at or near the beginning of paragraphs is a fine strategy, especially for beginning writers. If you announce a topic clearly and early on in a paragraph, your readers are likely to grasp your idea and to make the connections that you want them to make.",


"With this mind, take some time to contemplate the diagrams in the figure below.The widset point of each diagram represents the topic sentence of the paragraph.As details are presented, the topic becomes narrower and more focsed.The topic can precede the details, it cam follow them, it can both precede and follow them,or the details can surround the topic.There are surely more alternatives than those that are presented here, but this gives you an idea of some of the possible paragraph structures and possible placement for the topic sentence of the paragraph.",

"The decision about what to put into your paragraph begins with the germination of a seed of idea, this germination process is better known as brainstroming.There are many techniques for brainstroming, whichever one you choose, this stage of paragraph development cannot be skipped.Building paragraph can be like building a skyscraper, there must be a well-planned foundation that supports what you are building.Any cracks inconsistencies, or other corruptions of the foundation can cause your whole paper to crumble.",

"Although most people consider piranhas to be quite dangerous, they are, except in two main situations, entirely harmless. Piranhas rarely feed on large animals; they eat smaller fish and aquatic plants. When confronted with humans, piranhas instinct is to flee, not attack. But there are two situations in which a piranha bite is likely. The first is when a frightened piranha is lifted out of the water for example, if it has been caught in a fishing net. The second is when the water level in pools where piranhas are living falls too low.",

"Python conditional statements are used to make decisions based on certain conditions. They allow the program to execute specific blocks of code when a codition evaluates to true.Python loops are used to execute a block of code repeatedly, either for a fixed number of times or until a condition is met.In this section of python tutorial,we will explore python condition logic and python loops.Here we will explore python loop constructs, including for and while loops, along with essential loop control statements like break, continue and pass.",

"Python quiz page covers topics including variables, data types and how to manage output effectively. You'll explore operators and control flow to structure our code, along with loops (for and while) for repetitive tasks. Additionally, you'll gain knowledge with Python data structures such as lists, tuples, dictionaries and sets.This python tutorial is designed for biginners, but it helps if you already have some basic knowledge of programming concepts like variable, commands and syntax.",

"Connects the dots and show how the example is relevant to the central point.Always unite the furthest link to the idea.This idea holds every point together unified.Do not leave any of your examples unexplained.You might be able to explain the relationship between the example and the topic sentence in the same sentence which introduced the example. More often, however , you will need to explain that relationship in a separate sentence.If we have to put our examples now in one paragraph writing,here how it looks like.",

"This is when the writer is narrating an incident or story through the essay. So these are in the first person. The aim when writing narrative essays is to involve the reader in them as if they were right there when it was happening. So make them as vivid and real as possible. One way to make this possible is to follow the principle of show, don’t tell. So you must involve the reader in the story.",

" Here the writer will describe a place, an object, an event or maybe even a memory. But it is not just plainly describing things. The writer must paint a picture through his words. One clever way to do that is to evoke the senses of the reader. Do not only rely on sight but also involve the other senses of smell, touch, sound etc. A descriptive essay when done well will make the reader feel the emotions the writer was feeling at the moment.",

"Infinite intelligence leads and guides me in all my ways.Perfect health is mine, and the Law of Harmony operates in my mind and body.Beauty,love,peace, and abundance are mine.The principles of right action and divine order govern my entire life.I know my major premise is based on the eternal truths of life, and I know ,feel, and believe that my subconscious mind responds according to the nature of my conscious mind's thinking.This professor formulated an overall picture of the way he wanted his life to be. This was his major premise.",
   
];